//Got the data from https://github.com/christkv/ecommerce/blob/master/preload_data/products.json. We took only the information we felt we required.
const games = [
  {
    "id": 1,
    "simgurl": "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL.jpg",
    "imgwidth": 500,
    "imgheight": 467,
    "brand": "Encore Software",
    "age": "Mature",
    "feature1": "Sequel to the original Assassin's Creed continues the storyline as you fight to uncover a conspiracy bigger than you could imagine",
    "feature2": "Utilize an arsenal of weapons",
    "feature3": "You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.",
    "genre": "Action",
    "price": 999,
    "model": 26732,
    "title": "Assassin's creed I & II",
    "ranking": 1187,
    "warranty": ""
  },
  {
    "id": 2,
    "simgurl": "http://ecx.images-amazon.com/images/I/41kXCp%2BUyeL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41kXCp%2BUyeL.jpg",
    "imgwidth": 353,
    "imgheight": 500,
    "brand": "Blizzard Entertainment",
    "age": "Mature",
    "feature1": "The Witch Doctor is a new character reminiscent of the Diablo II Necromancer",
    "feature2": "The Barbarians will have a variety of revamped skills at their disposal based on the use of their incredible physical prowess.",
    "feature3": "1-on-1 dueling system coming into play.",
    "genre": "Adventure",
    "price": 3999,
    "model": 728515,
    "title": "Diablo III - PC",
    "ranking": 69,
    "warranty": ""
  },
  {
    "id": 3,
    "simgurl": "http://ecx.images-amazon.com/images/I/51Ba653B6ZL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51Ba653B6ZL.jpg",
    "imgwidth": 355,
    "imgheight": 500,
    "brand": "Bethesda",
    "age": "Mature",
    "feature1": "Take in the sights and sounds of the vast Capital Wasteland! See the great monuments of the United States lying in post-apocalyptic ruin!",
    "feature2": "Vault-Tec engineers bring you the latest in human ability simulation - the SPECIAL Character System! Utilizing new breakthroughs in points-based ability representation, SPECIAL affords unlimited customization of your character.",
    "feature3": "The wizards at Vault-Tec have done it again! No longer constrained to just one view, experience the world from 1st or 3rd person perspective.",
    "genre": "Action",
    "price": 1999,
    "model": 12969,
    "title": "Fallout 3: Game of The Year Edition (PC)",
    "ranking": 1229,
    "warranty": ""
  },
  {
    "id": 4,
    "simgurl": "http://ecx.images-amazon.com/images/I/416xeHGXbUL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/416xeHGXbUL.jpg",
    "imgwidth": 352,
    "imgheight": 500,
    "brand": "Activision",
    "age": "Mature",
    "feature1": "An all-new Call of Duty - Black Ops storyline featuring new characters and returning characters",
    "feature2": "Unique single-player campaign that contains two time periods linked by characters and their actions",
    "feature3": "Special Strike Force missions, in which the players action affect the outcome of gameplay and the overall campaign",
    "genre": "Adventure",
    "price": 5999,
    "model": 33349,
    "title": "Call of Duty: Black Ops II - PC",
    "ranking": 1745,
    "warranty": ""
  },
  {
    "id": 5,
    "simgurl": "http://ecx.images-amazon.com/images/I/51N7GT9BQ%2BL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51N7GT9BQ%2BL.jpg",
    "imgwidth": 354,
    "imgheight": 500,
    "brand": "Electronic Arts",
    "age": "Mature",
    "feature1": "Seven Wonders of the Urban Rainforest - New York City has been contained in a giant nanodome and grown into a unique rainforest with seven distinct environments. Master the ultimate sandbox and turn it into your own personal hunting ground.",
    "feature2": "Assess, Adapt, and Attack - Crysis's highly-acclaimed sandbox gameplay is back with more open levels to let players choose their path and approach. Your upgraded Nanosuit allows brute force or stealth, always giving you more than one option.",
    "feature3": "Expanded Multiplayer - Experiment with new ways to customize your Nanosuit and brand new game modes.",
    "genre": "Action",
    "price": 5999,
    "model": 19810,
    "title": "Crysis 3 - PC",
    "ranking": 980,
    "warranty": ""
  },
  {
    "id": 6,
    "simgurl": "http://ecx.images-amazon.com/images/I/517S6KnRpOL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/517S6KnRpOL.jpg",
    "imgwidth": 353,
    "imgheight": 500,
    "brand": "Electronic Arts",
    "age": "Everyone 10+",
    "feature1": "Epic journey from the origin and evolution of life through the development of civilization and technology and outer space exploration",
    "feature2": "Play any way you choose in the five evolutionary phases of Spore: Cell, Creature, Tribe, Civilization, and Space",
    "feature3": "Grow, evolve, interact with and battle other cultures, and conquer the planet",
    "genre": "Role Playing",
    "price": 1999,
    "model": 15352,
    "title": "Spore - PC/Mac",
    "ranking": 1028,
    "warranty": ""
  },
  {
    "id": 7,
    "simgurl": "http://ecx.images-amazon.com/images/I/418h3hauXWL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/418h3hauXWL.jpg",
    "imgwidth": 500,
    "imgheight": 380,
    "brand": "Microsoft",
    "age": "Everyone 5+",
    "feature1": "Play in comfort - A compact, ergonomic shape lets you play comfortably for hours on your PC.",
    "feature2": "Feel the action - Vibration feedback gives you a riveting gaming experience.",
    "feature3": "PC gaming at its best - Precise thumb sticks, two pressure-point triggers, and an 8-way directional pad help you stay in control.",
    "genre": "Action",
    "price": 3995,
    "model": "52A-00004",
    "title": "Microsoft Xbox 360 Controller for Windows",
    "ranking": 0,
    "warranty": ""
  },
  {
    "id": 8,
    "simgurl": "http://ecx.images-amazon.com/images/I/31NhIzIMrUL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/31NhIzIMrUL.jpg",
    "imgwidth": 400,
    "imgheight": 400,
    "brand": "Gator Crunch",
    "age": "Everyone",
    "feature1": "USB Game Controller - Works with both PS3 and PC",
    "feature2": "Save money using a wired controller",
    "feature3": "Ideal for the price aware consumer",
    "genre": "Equipment",
    "price": 2999,
    "model": "GC-PS3WCUSB",
    "title": "Game Controller for PC or PlayStation 3 (PS3) - (Lifetime Warranty, Bulk Packaging)",
    "ranking": 675,
    "warranty": ""
  },
  {
    "id": 9,
    "simgurl": "http://ecx.images-amazon.com/images/I/51UfXhiC61L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51UfXhiC61L.jpg",
    "imgwidth": 377,
    "imgheight": 500,
    "brand": "Activision",
    "age": "Mature",
    "feature1": "Next-gen engine ushers in an unprecedented level of innovation, delivering stunning and lifelike characters, gorgeously rendered environments, and authentic real-world animations, all brought to life by advanced lighting systems and visual effects",
    "feature2": "Players will take on the underdog role with Call of Duty - Ghosts; outnumbered and outgunned, players must fight to reclaim a fallen nation in an intensely personal narrative. Gamers will get to know an entirely new cast of characters and locales in a world unlike any that Call of Duty has explored before",
    "feature3": "Dynamic maps bring earthquakes, floods, and user-initiated events that fundamentally alter the flow and strategy of every fight",
    "genre": "Action",
    "price": 5999,
    "model": 33451,
    "title": "Call of Duty: Ghosts - PC",
    "ranking": 1425,
    "warranty": ""
  },
  {
    "id": 10,
    "simgurl": "http://ecx.images-amazon.com/images/I/51DeQeU7MiL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51DeQeU7MiL.jpg",
    "imgwidth": 354,
    "imgheight": 500,
    "brand": "Bethesda",
    "age": "Mature",
    "feature1": "Skyrim reimagines the open-world fantasy epic, pushing the game play and technology of a virtual world to new heights",
    "feature2": "Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling",
    "feature3": "Skyrim's new game engine brings to life a complete virtual world with rolling clouds, rugged mountains, bustling cities, lush fields",
    "genre": "Role Playing",
    "price": 1999,
    "model": 11761,
    "title": "Elder Scrolls V: Skyrim - PC",
    "ranking": 845,
    "warranty": ""
  },
  {
    "id": 11,
    "simgurl": "http://ecx.images-amazon.com/images/I/51oVHnYTr8L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51oVHnYTr8L.jpg",
    "imgwidth": 500,
    "imgheight": 494,
    "brand": "Sony",
    "age": "Mature",
    "feature1": "The PlayStation 3 Grand Theft Auto V Bundle includes the fifth installment of one of the best selling franchises of all time, Grand Theft Auto.",
    "feature2": "Bundle Contents: PlayStation3 System 500GB",
    "feature3": "Los Santos: a sprawling metropolis full of self-help gurus, starlets and fading celebrities struggling to stay afloat in an era of economic uncertainty and cheap cable TV. Amidst the turmoil, three very different criminals risk everything in a series of daring and dangerous heists that could set them up for life.",
    "genre": "Action",
    "price": 26999,
    "model": 99288,
    "title": "PS3 500 GB Grand Theft Auto V Bundle",
    "ranking": 981,
    "warranty": "2 year warrenty"
  },
  {
    "id": 12,
    "simgurl": "http://ecx.images-amazon.com/images/I/41xAAzZeMbL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41xAAzZeMbL.jpg",
    "imgwidth": 500,
    "imgheight": 355,
    "brand": "Sony",
    "age": "Kids to Adults",
    "feature1": "Play. Stream. Watch. Amazing Value at a Low Price: Play the largest highest rated games library, Stream services like Amazon Instant Video, Netflix, and Hulu and Watch HD Blu-ray on the PlayStation 3 12GB System for $199.",
    "feature2": "This Generation's Largest Exclusive Games Library: Dig into this platform generation's most extensive library of exclusive games, including popular titles like LittleBigPlanet and award-winning AAA series such as God of War and Uncharted.",
    "feature3": "Play Online for no Additional Fee: Use an online connection to access PlayStation Network's free* multiplayer. Bluetooth EDR capability makes communication easy and clear when you're teaming up with friends *User is responsible for internet access fees",
    "genre": "Action",
    "price": 19999,
    "model": 99242,
    "title": "Sony Computer Entertainment Playstation 3 12GB System",
    "ranking": 478,
    "warranty": ""
  },
  {
    "id": 13,
    "simgurl": "http://ecx.images-amazon.com/images/I/41E3Nf1xm7L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41E3Nf1xm7L.jpg",
    "imgwidth": 500,
    "imgheight": 221,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "Save over $165 with the Game of the Year PlayStation 3 Bundle including a 250GB PS3 System, Batman: Arkham Origins, and The Last of Us.",
    "feature2": "With over 40 perfect scores, The Last of Us is one of the greatest games made- Only On PlayStation",
    "feature3": "Batman: Arkham Origins includes the Knightfall Pack featuring 5 all new challenge maps and two skins- the Knightfall Batman and Classic TV Series Batman- Only On PlayStation for a limited Time",
    "genre": "Action",
    "price": 25000,
    "model": 3000074,
    "title": "PlayStation 3 The Last of Us & Batman: Arkham Origins Bundle",
    "ranking": 782,
    "warranty": ""
  },
  {
    "id": 14,
    "simgurl": "http://ecx.images-amazon.com/images/I/61wNDTpNBXL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/61wNDTpNBXL.jpg",
    "imgwidth": 500,
    "imgheight": 498,
    "brand": "Sony",
    "age": "Everyone 5+ - Mature",
    "feature1": "Play one of the highest rated games of 2013 with The Last of Us PlayStation3 Bundle",
    "feature2": "With over 40 perfect scores, The Last of Us is one of the great games made- Only On PlayStation",
    "feature3": "The PlayStation3 system includes a free PlayStationNetwork account for online gaming, streaming movies and music, and access to the PlayStation Store. -Internet Access Required",
    "genre": "Action",
    "price": 24900,
    "model": 3000079,
    "title": "PS3 250GB The Last of Us Bundle",
    "ranking": 1219,
    "warranty": ""
  },
  {
    "id": 15,
    "simgurl": "http://ecx.images-amazon.com/images/I/51Q2xrhtJWL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51Q2xrhtJWL.jpg",
    "imgwidth": 500,
    "imgheight": 491,
    "brand": "Console",
    "age": "Everyone",
    "feature1": "",
    "feature2": "",
    "feature3": "",
    "genre": "Action",
    "price": 29999,
    "model": 98418,
    "title": "Sony Playstation 3",
    "ranking": 300,
    "warranty": ""
  },
  {
    "id": 16,
    "simgurl": "http://ecx.images-amazon.com/images/I/41eMP8po-ML._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41eMP8po-ML.jpg",
    "imgwidth": 500,
    "imgheight": 381,
    "brand": "Sony",
    "age": "Everyone",
    "feature1": "The Azurite Blue PlayStation 3 250GB System includes an Azurite Blue DualShock 3 controller.",
    "feature2": "Play one of the highest rated games of 2013 with PlayStation All-Stars Battle Royale Bundle",
    "feature3": "PlayStation All-Stars Battle Royale is one of the great games made- Only On PlayStation",
    "genre": "Action",
    "price": 24999,
    "model": 2384,
    "title": "PS3 Azurite 250GB System with PlayStation All-Stars Battle Royale Bundle",
    "ranking": 579,
    "warranty": ""
  },
  {
    "id": 17,
    "simgurl": "http://ecx.images-amazon.com/images/I/41Ev0ryNToL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41Ev0ryNToL.jpg",
    "imgwidth": 500,
    "imgheight": 496,
    "brand": "Sony",
    "age": "Everyone",
    "feature1": "New slimmer, lighter PS3 system, Wireless controller",
    "feature2": "320GB HDD for storing games, music, videos, and photos",
    "feature3": "Streams thousands of movies and TV shows instantly from Netflix",
    "genre": "Action",
    "price": 29999,
    "model": 98424,
    "title": "PlayStation 3 320GB System",
    "ranking": 1286,
    "warranty": "A one (1) year manufacturer warranty still exists, will expire March of 2013."
  },
  {
    "id": 18,
    "simgurl": "http://ecx.images-amazon.com/images/I/616OOnZv-5L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/616OOnZv-5L.jpg",
    "imgwidth": 500,
    "imgheight": 498,
    "brand": "Sony",
    "age": "Mature",
    "feature1": "Experience unbelievably realistic graphics, physics, and animations powered by the PlayStation 3 system and Ubisoft's new Anvil Next engine.",
    "feature2": "Take part in Assassin's Creed III's endlessly thrilling online multiplayer modes for free on the PlayStation Network",
    "feature3": "Download updates and new content with the PlayStation 3 system's massive 500GB hard drive which holds up to 3750 games, 297 movies, 198,437 songs, and 80,000 photos.",
    "genre": "Action",
    "price": 29999,
    "model": 99105,
    "title": "PS3 500 GB Assassin's Creed III Bundle",
    "ranking": 4356,
    "warranty": ""
  },
  {
    "id": 19,
    "simgurl": "http://ecx.images-amazon.com/images/I/41tWPDyXWZL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41tWPDyXWZL.jpg",
    "imgwidth": 400,
    "imgheight": 400,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "Slim 250GB PS3 System",
    "feature2": "PlayStation Move controller",
    "feature3": "PlayStation Eye camera",
    "genre": "Action",
    "price": 34999,
    "model": "YG83022",
    "title": "Sony Playstation 3 250GB Sports Champion & EyePet Move Bundle",
    "ranking": 2295,
    "warranty": ""
  },
  {
    "id": 20,
    "simgurl": "http://ecx.images-amazon.com/images/I/612F-7C91cL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/612F-7C91cL.jpg",
    "imgwidth": 500,
    "imgheight": 492,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "The 250GB PlayStation3 System, with a built in Blu-Ray player, can hold over to 1800 Games, 140 Movies, 99,000 Songs, and 40,000 photos, or a mixture of all",
    "feature2": "UNCHARTED 3: Drake's Deception Game of the Year Edition showcases Nathan Drake's journey through new challenges and includes Bonus Content",
    "feature3": "The 1-Year Membership to PlayStation Plus gives you access to 12 Hit games, exclusive Game Betas, discounts of up to 75% on the PlayStation Store, and much much more",
    "genre": "Action",
    "price": 26999,
    "model": 99264,
    "title": "PS3 250 GB Uncharted 3 and PS Plus Bundle",
    "ranking": 8394,
    "warranty": ""
  },
  {
    "id": 21,
    "simgurl": "http://ecx.images-amazon.com/images/I/41omR-LTnaL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41omR-LTnaL.jpg",
    "imgwidth": 393,
    "imgheight": 500,
    "brand": "Sony",
    "age": "Kids to Adults",
    "feature1": "The PlayStation 4 was released on November 15, 2013.",
    "feature2": "PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a platform that is tuned specifically to their needs",
    "feature3": "Engage in endless personal challenges between you and your community, and share your epic moments for the world to see",
    "genre": "Action",
    "price": 39999,
    "model": 10034,
    "title": "PlayStation 4 Console",
    "ranking": 4,
    "warranty": "contact sony for details"
  },
  {
    "id": 22,
    "simgurl": "http://ecx.images-amazon.com/images/I/41dn1krPyAL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41dn1krPyAL.jpg",
    "imgwidth": 500,
    "imgheight": 334,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "The official release date for the PlayStation 4 is November 15, 2013. Confirmed orders will arrive at your shipping address based on the shipping speed selected.",
    "feature2": "PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a platform that is tuned specifically to their needs.",
    "feature3": "Engage in endless personal challenges between you and your community, and share your epic moments for the world to see.",
    "genre": "Action",
    "price": 45999,
    "model": "E3PlayStation4DS4playstation_4",
    "title": "PlayStation 4 DualShock 4 Bundle",
    "ranking": 804,
    "warranty": ""
  },
  {
    "id": 23,
    "simgurl": "http://ecx.images-amazon.com/images/I/41Su-%2BvWPRL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41Su-%2BvWPRL.jpg",
    "imgwidth": 500,
    "imgheight": 334,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "The official release date for the PlayStation 4 is November 15, 2013. Confirmed orders will arrive at your shipping address based on the shipping speed selected.",
    "feature2": "PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a platform that is tuned specifically to their needs",
    "feature3": "Engage in endless personal challenges between you and your community, and share your epic moments for the world to see",
    "genre": "Action",
    "price": 45998,
    "model": "E3PlayStation4Knackplaystation_4",
    "title": "PlayStation 4 Knack Launch Day Bundle",
    "ranking": 2519,
    "warranty": ""
  },
  {
    "id": 24,
    "simgurl": "http://ecx.images-amazon.com/images/I/41nkwHrns7L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41nkwHrns7L.jpg",
    "imgwidth": 500,
    "imgheight": 334,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "The official release date for the PlayStation 4 is November 15, 2013. Confirmed orders will arrive at your shipping address based on the shipping speed selected.",
    "feature2": "PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a platform that is tuned specifically to their needs",
    "feature3": "Engage in endless personal challenges between you and your community, and share your epic moments for the world to see",
    "genre": "Action",
    "price": 50997,
    "model": "E3PlayStation4Killzoneplaystation_4",
    "title": "PlayStation 4 Killzone Launch Day Bundle",
    "ranking": 741,
    "warranty": ""
  },
  {
    "id": 25,
    "simgurl": "http://ecx.images-amazon.com/images/I/41kxtajfNZL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41kxtajfNZL.jpg",
    "imgwidth": 500,
    "imgheight": 334,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "The official release date for the PlayStation 4 is November 15, 2013. Confirmed orders will arrive at your shipping address based on the shipping speed selected.",
    "feature2": "PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a platform that is tuned specifically to their needs",
    "feature3": "Engage in endless personal challenges between you and your community, and share your epic moments for the world to see",
    "genre": "Action",
    "price": 50997,
    "model": "E3PlayStation4Battlefield4playstation_4",
    "title": "PlayStation 4 Battlefield 4 Launch Day Bundle",
    "ranking": 1398,
    "warranty": ""
  },
  {
    "id": 26,
    "simgurl": "http://ecx.images-amazon.com/images/I/4119fqsLsgL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/4119fqsLsgL.jpg",
    "imgwidth": 500,
    "imgheight": 313,
    "brand": "Sony",
    "age": "Everyone",
    "feature1": "The feel, shape, and sensitivity of the dual analog sticks and trigger buttons have been improved to provide a greater sense of control.",
    "feature2": "The new multi-touch and clickable touch pad on the face of the DualShock 4 Wireless Controller opens up worlds of new gameplay possibilities.",
    "feature3": "The DualShock 4 Wireless Controller features a built-in speaker and stereo headset jack.",
    "genre": "Action",
    "price": 5999,
    "model": 10037,
    "title": "PlayStation 4 Dualshock 4 Wireless Controller",
    "ranking": 13,
    "warranty": ""
  },
  {
    "id": 27,
    "simgurl": "http://ecx.images-amazon.com/images/I/51cENOhHCXL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51cENOhHCXL.jpg",
    "imgwidth": 421,
    "imgheight": 500,
    "brand": "Activision",
    "age": "Mature",
    "feature1": "A new Call of Duty Universe",
    "feature2": "The next generation of multiplayer",
    "feature3": "",
    "genre": "Action",
    "price": 5999,
    "model": 84679,
    "title": "Call of Duty: Ghosts - PlayStation 4",
    "ranking": 46,
    "warranty": ""
  },
  {
    "id": 28,
    "simgurl": "http://ecx.images-amazon.com/images/I/21g0FaPsY3L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/21g0FaPsY3L.jpg",
    "imgwidth": 500,
    "imgheight": 333,
    "brand": "Sony",
    "age": "Everyone 5+",
    "feature1": "When combined with the DualShock 4 Wireless Controller's light bar, the evolutionary 3D depth-sensing technology in the PlayStation Camera allows it to precisely track a player's position in the room",
    "feature2": "From navigational voice commands to facial recognition, the PlayStation Camera adds incredible innovation to your gaming.",
    "feature3": "Automatically integrate a picture-in-picture video of yourself during gameplay broadcasts, and challenge your friends during play",
    "genre": "Action",
    "price": 5999,
    "model": 10053,
    "title": "PlayStation 4 Camera",
    "ranking": 118,
    "warranty": ""
  },
  {
    "id": 29,
    "simgurl": "http://ecx.images-amazon.com/images/I/51x2M9TsVHL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51x2M9TsVHL.jpg",
    "imgwidth": 392,
    "imgheight": 500,
    "brand": "Ubisoft",
    "age": "Mature",
    "feature1": "EXPLORE AN OPEN WORLD FILLED WITH OPPORTUNITIES: Discover the most diverse Assassin's Creed world ever created. From Kingston to Nassau, explore 50 unique locations where you can live the life of a pirate.",
    "feature2": "BECOME THE MOST FEARED PIRATE IN THE CARIBBEAN: Command your ship, the Jackdaw, and strike fear in all who see her. Plunder and pillage to upgrade the Jackdaw with ammunition and equipment needed to fight off enemy ships.",
    "feature3": "MULTIPLAYER EXPERIENCE: Play with your friends in the ruthless and critically acclaimed multiplayer experience. Choose from an eclectic cast of characters from the Golden Age of Pirates and fight to the death in exotic locations.",
    "genre": "Action",
    "price": 5999,
    "model": 35811,
    "title": "Assassin's Creed IV Black Flag - PlayStation 4",
    "ranking": 83,
    "warranty": ""
  },
  {
    "id": 30,
    "simgurl": "http://ecx.images-amazon.com/images/I/51Ud6LBTOIL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51Ud6LBTOIL.jpg",
    "imgwidth": 414,
    "imgheight": 500,
    "brand": "Electronic Arts",
    "age": "Everyone",
    "feature1": "Pure Shot - Shooting has been transformed. Players have the intelligence to adjust their stride and approach angle to find the best position for hitting the back of the net. Well-hit balls feel satisfying and goals are rewarding. As well as quality strikes, players can now shoot while off-balance or rushed.",
    "feature2": "Real Ball Physics - Strike the ball with more force and finesse. Realistic ball physics now determines the trajectories of balls in game, enabling players to strike the ball with force from distance, drill low rising shots with accuracy, and blast dipping or swerving shots, just like real soccer players",
    "feature3": "Protect The Ball - Dominate midfield and dictate the tempo of a match. Fend-off and block defenders from the ball while dribbling at any speed. Protect the ball from opponents to control play through midfield and dictate the pace of the match. Plus, out-muscle opponents for position before receiving the ball, then turn defenders to carve out opportunities.",
    "genre": "Sports",
    "price": 5999,
    "model": 73069,
    "title": "FIFA 14 - PlayStation 4",
    "ranking": 66,
    "warranty": ""
  },
  {
    "id": 31,
    "simgurl": "http://ecx.images-amazon.com/images/I/51dfEFhfknL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51dfEFhfknL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Nintendo",
    "age": "Everyone",
    "feature1": "The Wii U Game pad breaks down barriers between you and your entertainment with a 6.2\" 16:9 LCD touch screen, motion control system, front-facing camera, microphone, stereo speakers, rumble feature, button controls and analog sticks",
    "feature2": "Console works with most games from the original Wii console, as well as the Wii Remote, Wii Remote Plus, Nunchuk controllers, Balance Board and many other Wii accessories, so you can continue to enjoy your favorite Wii features",
    "feature3": "In Super Mario Bros. U, swoop through levels and cling to walls when Mario transforms into Flying Squirrel Mario, or gently float through the air while hanging onto Tiny Balloon Yoshi.",
    "genre": "Action",
    "price": 29999,
    "model": "WUPSKAFP",
    "title": "Nintendo Wii U 32GB Mario & Luigi Deluxe Set",
    "ranking": 156,
    "warranty": "30 Days"
  },
  {
    "id": 32,
    "simgurl": "http://ecx.images-amazon.com/images/I/41ugCvxSD8L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41ugCvxSD8L.jpg",
    "imgwidth": 500,
    "imgheight": 346,
    "brand": "Nintendo",
    "age": "Everyone 5+",
    "feature1": "",
    "feature2": "",
    "feature3": "",
    "genre": "Action",
    "price": 34999,
    "model": "WUPSKAFB",
    "title": "Nintendo Wii U Console - 32GB Black Deluxe Set",
    "ranking": 821,
    "warranty": "Warranty is from Manufacturer."
  },
  {
    "id": 33,
    "simgurl": "http://ecx.images-amazon.com/images/I/51QdN4zCTEL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51QdN4zCTEL.jpg",
    "imgwidth": 500,
    "imgheight": 345,
    "brand": "Nintendo",
    "age": "Everyone 5+",
    "feature1": "For the first time, experience your favorite Nintendo worlds in crystal clear high definition",
    "feature2": "The New Wii U GamePad controller incorporates a 6.2-inch, 16:9 aspect ratio LCD touch screen, as well as traditional button controls and two analog sticks",
    "feature3": "Use the Wii U Gamepad to view gameplay on both your TV and the gamepad, as another perspective on gameplay, or use it and 4 Wii remotes for 5 player gameplay",
    "genre": "Action",
    "price": 29999,
    "model": "WUPSKAFL",
    "title": "The Legend of Zelda™: The Wind Waker (HD Deluxe Set)",
    "ranking": 1151,
    "warranty": ""
  },
  {
    "id": 34,
    "simgurl": "http://ecx.images-amazon.com/images/I/41OZov495IL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41OZov495IL.jpg",
    "imgwidth": 500,
    "imgheight": 346,
    "brand": "Nintendo",
    "age": "Everyone 5+",
    "feature1": "Four USB 2.0 connector slots are included. The new console is backward compatible with Wii games and Wii accessories.",
    "feature2": "IBM Power-based multi-core microprocessor.",
    "feature3": "Up to four Wii Remote (or Wii Remote Plus) controllers can be connected at once. The new console supports all Wii controllers and input devices, including the Nunchuk™ controller, Classic Controller, Classic Controller Pro and Wii Balance Board.",
    "genre": "Action",
    "price": 29999,
    "model": "WUPSWAAB",
    "title": "Nintendo Wii U Console 8GB Basic Set - White",
    "ranking": 2786,
    "warranty": ""
  },
  {
    "id": 35,
    "simgurl": "http://ecx.images-amazon.com/images/I/512XpOaLu2L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/512XpOaLu2L.jpg",
    "imgwidth": 355,
    "imgheight": 500,
    "brand": "Ubisoft",
    "age": "Mature",
    "feature1": "Two Screens, Twice The Fear - Feel the tension mount as you try to keep an eye on your TV and controller screen.",
    "feature2": "Survival-Horror Action At Its Best - Resources are in short supply while your enemies are legion, and you never know when you will find more weapons, ammunition, first aid and food.",
    "feature3": "Don't Leave Home Without Your BOB: The new WiiU controller becomes your Bug-Out Bag, the ultimate all-in-one survival kit for your tools, inventory, med kits, maps and more.",
    "genre": "Action",
    "price": 5999,
    "model": 18719,
    "title": "ZombiU - Nintendo Wii U",
    "ranking": 574,
    "warranty": ""
  },
  {
    "id": 36,
    "simgurl": "http://ecx.images-amazon.com/images/I/6109S9vOSCL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/6109S9vOSCL.jpg",
    "imgwidth": 356,
    "imgheight": 500,
    "brand": "D3 Publisher",
    "age": "Everyone 10+",
    "feature1": "Series creator Pendleton Ward and developer WayForward team up again with a brand new storyline and an offbeat, fun adventure for fans of all ages",
    "feature2": "Play as fan-favorite Adventure Time characters Finn, Jake, Marceline and Cinnamon Bun plus many more, each one with unique moves and an arsenal of creative attacks",
    "feature3": "Characters come to life with voiceovers provided by the original TV cast",
    "genre": "Adventure",
    "price": 3995,
    "model": 30511,
    "title": "Adventure Time: Explore the Dungeon Because I DON'T KNOW! WiiU",
    "ranking": 4667,
    "warranty": ""
  },
  {
    "id": 37,
    "simgurl": "http://ecx.images-amazon.com/images/I/51kw%2BUcBZzL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51kw%2BUcBZzL.jpg",
    "imgwidth": 355,
    "imgheight": 500,
    "brand": "Ubisoft",
    "age": "Mature",
    "feature1": "As a Native American assassin, eliminate your enemies with guns, bows, tomahawks, and more!",
    "feature2": "From bustling city streets to the chaotic battlefields, play a critical role in the most legendary events of the American Revolution including the Battle of Bunker Hill and Great Fire of New York",
    "feature3": "Introducing the Ubisoft-AnvilNext game engine, the stunning new technology that will revolutionize gaming with powerful graphics, lifelike animations, immersive combat, and advanced physics",
    "genre": "Adventure",
    "price": 1999,
    "model": 18723,
    "title": "Assassin's Creed III - Nintendo Wii U",
    "ranking": 1152,
    "warranty": ""
  },
  {
    "id": 38,
    "simgurl": "http://ecx.images-amazon.com/images/I/616iMUgGCIL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/616iMUgGCIL.jpg",
    "imgwidth": 356,
    "imgheight": 500,
    "brand": "Sega",
    "age": "Everyone 10+",
    "feature1": "New and improved Color Powers; Sonic can now fly through the air, tear up levels and explode into enemies; He's more powerful than ever",
    "feature2": "Speed through a variety of exhilarating levels; Explore massive mind-bending courses, vast underground tunnels and colossal structures in the sky as you run inside, outside and upside down",
    "feature3": "Save the world one fight at a time; Take on each of the devious Deadly Six in dynamic boss battles which test all of Sonic's moves and power-ups",
    "genre": "Action",
    "price": 4995,
    "model": 67106,
    "title": "Sonic Lost World WiiU",
    "ranking": 1085,
    "warranty": ""
  },
  {
    "id": 39,
    "simgurl": "http://ecx.images-amazon.com/images/I/51bpucF013L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51bpucF013L.jpg",
    "imgwidth": 350,
    "imgheight": 500,
    "brand": "Nintendo",
    "age": "Everyone",
    "feature1": "Each character has unique abilities and play styles. For example, Princess Peach glides over gaps, while Luigi has his trademark extra-high jump.",
    "feature2": "The new cat transformation allows players to run on all fours, pounce on enemies, attack in midair, or use their claws to scamper up walls and goal poles.",
    "feature3": "Explore colorful 3D environments filled with obstacles and contraptions like transparent pipes and vertical conveyor belts, which add new puzzle elements.",
    "genre": "Action",
    "price": 5999,
    "model": "WUPPARDE",
    "title": "Super Mario 3D World - Nintendo Wii U",
    "ranking": 102,
    "warranty": ""
  },
  {
    "id": 40,
    "simgurl": "http://ecx.images-amazon.com/images/I/51KQRPq8cKL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51KQRPq8cKL.jpg",
    "imgwidth": 356,
    "imgheight": 500,
    "brand": "Namco",
    "age": "Everyone 10+",
    "feature1": "Animated series based story line: The epic battle follows an original story line inspired from the highly anticipated animated series launching this summer",
    "feature2": "Characters and environments: A huge all-new cast of characters, good and evil, all developed from the animated series; As well as brand new settings shown in the series as well",
    "feature3": "Unique Pac-Man power-ups: Pac will need to utilize a host of new and unique power-ups to stop the ghosts and defeat the evil bosses",
    "genre": "Adventure",
    "price": 1999,
    "model": 81004,
    "title": "Pac-Man and the Ghostly Adventures - Nintendo Wii U",
    "ranking": 1661,
    "warranty": ""
  },
  {
    "id": 41,
    "simgurl": "http://ecx.images-amazon.com/images/I/310D-sfUdXL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/310D-sfUdXL.jpg",
    "imgwidth": 372,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone 5+",
    "feature1": "Xbox 360 E console",
    "feature2": "1 Black Wireless Controller",
    "feature3": "Built in Wi-Fi",
    "genre": "Action",
    "price": 19999,
    "model": "L9V-00001",
    "title": "Xbox 360 4GB",
    "ranking": 132,
    "warranty": ""
  },
  {
    "id": 42,
    "simgurl": "http://ecx.images-amazon.com/images/I/411d9xAlGRL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/411d9xAlGRL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone",
    "feature1": "Sleek New Design, Xbox LIVE",
    "feature2": "4GB internal memory, Kinect Ready",
    "feature3": "Built-in Wi-Fi, Xbox 360 wireless controller (black)",
    "genre": "Action",
    "price": 19999,
    "model": "Standard",
    "title": "Xbox 360 4GB Console",
    "ranking": 396,
    "warranty": "1 year limited warranty on console"
  },
  {
    "id": 43,
    "simgurl": "http://ecx.images-amazon.com/images/I/41P3q1zb9tL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41P3q1zb9tL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone 5+",
    "feature1": "Xbox 4GB 360 E console with Kinect Sensor: The Xbox 360 console is sleek and quiet, with a stylish design that will be the centerpiece of your home entertainment system.",
    "feature2": "Includes two amazing games: Kinect Sports: Season Two, Kinect Adventures",
    "feature3": "Warranty: One year limited warranty on console (90 days on accessories)",
    "genre": "Adventure",
    "price": 29999,
    "model": "N7V-00001",
    "title": "Xbox 360 E 4GB Kinect Holiday Value Bundle",
    "ranking": 308,
    "warranty": ""
  },
  {
    "id": 44,
    "simgurl": "http://ecx.images-amazon.com/images/I/41EaIngkbqL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41EaIngkbqL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone",
    "feature1": "Xbox 360 250GB Hard Drive",
    "feature2": "Darksiders II",
    "feature3": "Xbox 360 Wireless Controller and Xbox 360 Headset",
    "genre": "Arcade",
    "price": 29999,
    "model": "R9G-00198",
    "title": "Xbox 360 250GB Spring Value Bundle",
    "ranking": 1346,
    "warranty": "90 days from date of purchase"
  },
  {
    "id": 45,
    "simgurl": "http://ecx.images-amazon.com/images/I/41mVXvLfOtL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41mVXvLfOtL.jpg",
    "imgwidth": 500,
    "imgheight": 380,
    "brand": "Microsoft",
    "age": "Everyone 5+",
    "feature1": "2.4GHz wireless technology with 30-foot range",
    "feature2": "Use up to four controllers simultaneously on one console,Requires 2 AA Batteries",
    "feature3": "Adjustable vibration feedback for longer battery life",
    "genre": "Action",
    "price": 4999,
    "model": "NSF-00001",
    "title": "Xbox 360 Wireless Controller - Glossy Black",
    "ranking": 14,
    "warranty": ""
  },
  {
    "id": 46,
    "simgurl": "http://ecx.images-amazon.com/images/I/41K2VDCPCNL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41K2VDCPCNL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone",
    "feature1": "20 GB Hard Drive",
    "feature2": "1 Wireless Controller",
    "feature3": "Sleek set-top design with horizontal or vertical placement option in a white finish",
    "genre": "Action",
    "price": 17999,
    "model": "52R-00030",
    "title": "Xbox 360 Pro 20 GB",
    "ranking": 876,
    "warranty": "out of manufacturer warranty, but the console was rebuilt cleaned new heat paste better heat syncs. its even better then before!"
  },
  {
    "id": 47,
    "simgurl": "http://ecx.images-amazon.com/images/I/51EYPFcLK9L._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51EYPFcLK9L.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone 10+",
    "feature1": "The infinite possibilities in Minecraft just got bigger! The gaming phenomenon comes to the console with new features designed specifically for Xbox 360.",
    "feature2": "Crafting has never been faster and easier! The new crafting interface in Minecraft for Xbox 360 delivers a completely new way to build Minecraft worlds where your imagination is the only limit.",
    "feature3": "Learn the basics and master essential skills faster with the all-new Tutorial mode.",
    "genre": "Adventure",
    "price": 1999,
    "model": "G2W-00001",
    "title": "Minecraft - Xbox 360",
    "ranking": 21,
    "warranty": ""
  },
  {
    "id": 48,
    "simgurl": "http://ecx.images-amazon.com/images/I/51nJFBcNbsL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/51nJFBcNbsL.jpg",
    "imgwidth": 480,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone",
    "feature1": "Xbox 360 250GB Console",
    "feature2": "Xbox 360 Wireless Controller Included",
    "feature3": "Bonus One-Month Xbox Live Gold Membership",
    "genre": "Racing",
    "price": 29999,
    "model": "Standard",
    "title": "Xbox 360 250GB Holiday Value Bundle",
    "ranking": 3836,
    "warranty": ""
  },
  {
    "id": 49,
    "simgurl": "http://ecx.images-amazon.com/images/I/510QQlrrvUL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/510QQlrrvUL.jpg",
    "imgwidth": 356,
    "imgheight": 500,
    "brand": "Rockstar Games",
    "age": "Mature",
    "feature1": "Players switch between characters constantly with a single button press, allowing them to see missions from different perspectives!",
    "feature2": "Players will be able to participate in multiple activities including yoga, triathlons, jet skiing, base jumping, tennis and golf!",
    "feature3": "Los Santos is the largest open world Rockstar has ever created!",
    "genre": "Adventure",
    "price": 5999,
    "model": 49124,
    "title": "Grand Theft Auto V - Xbox 360",
    "ranking": 24,
    "warranty": ""
  },
  {
    "id": 50,
    "simgurl": "http://ecx.images-amazon.com/images/I/41p3OktpwPL._SL160_.jpg",
    "limgurl": "http://ecx.images-amazon.com/images/I/41p3OktpwPL.jpg",
    "imgwidth": 500,
    "imgheight": 500,
    "brand": "Microsoft",
    "age": "Everyone",
    "feature1": "Xbox 360 Console",
    "feature2": "Xbox 360 250GB Hard Drive",
    "feature3": "Xbox 360 Wireless Controller",
    "genre": "Adventure",
    "price": 29999,
    "model": "RKH-00041",
    "title": "Xbox 360 250GB Console",
    "ranking": 943,
    "warranty": "STILL HAS 6 MONTH WARRANTY LEFT ON ON IT."
  }
]

export default games
